name: Run Model

on:
  push:
    branches:
      - final-report
  pull_request:
    branches:
      - final-report

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install Make
      - name: Install Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      # Run the Makefile
      - name: Run Makefile
        run: make run
