name: Verify Model Output

on:
  push:
    branches:
      - final-report
  pull_request:
    branches:
      - final-report

jobs:
  verify-model-output:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install Make
      - name: Install Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      # Run the Makefile and capture only model.py output
      - name: Run Makefile
        id: run-makefile
        run: |
          make run

      # Print model.py output log to the workflow logs
      - name: Print Model Output Log
        run: |
          echo "Contents of model_output.log:"
          cat model_output.log

      # Verify that the output contains the expected phrase
      - name: Verify Output
        run: |
          if ! grep -q "Accuracy with Selected Parameters:" model_output.log; then
            echo "Verification failed: Expected text not found in output"
            exit 1
          fi
